version: "3.8"

services:
  kiwi-db:
    image: mariadb:10.11
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: Flexxus2023**
      MYSQL_DATABASE: kiwi
      MYSQL_USER: flexxus
      MYSQL_PASSWORD: Flexxus2023**
    volumes:
      - kiwi-db-data:/var/lib/mysql
    networks:
      - traefik
    ports:
      - "6006:3306"  
    deploy:
      placement:
        constraints:
          - ${NODE}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 15s
      timeout: 5s
      retries: 10
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}

  kiwi:
    image: pub.kiwitcms.eu/kiwitcms/kiwi:latest
    environment:
      KIWI_DB_HOST: 10.250.0.68
      KIWI_DB_PORT: 6006
      KIWI_DB_NAME: kiwi
      KIWI_DB_USER: flexxus
      KIWI_DB_PASSWORD: Flexxus2023**
    volumes:
      - kiwi-uploads:/Kiwi/uploads
    networks:
      - traefik
    depends_on:
      - kiwi-db
    deploy:
      placement:
        constraints:
          - ${NODE}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${SERVICE_NAME}.entrypoints=web"
        - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAIN_NAME}`)"
        - "traefik.http.middlewares.${SERVICE_NAME}-http.redirectscheme.scheme=https"
        - "traefik.http.routers.${SERVICE_NAME}-https.rule=Host(`${DOMAIN_NAME}`)"
        - "traefik.http.routers.${SERVICE_NAME}-https.entrypoints=https"
        - "traefik.http.routers.${SERVICE_NAME}-https.tls=true"
        - "traefik.http.routers.${SERVICE_NAME}-https.tls.certresolver=myresolver"
        - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=8443"
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}

volumes:
  kiwi-db-data:
    driver: local
  kiwi-uploads:
    driver: local

networks:
  traefik:
    external: true
    name: traefik-network
